name: homechef_v3
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  geolocator: ^10.1.0
  bloc: ^8.1.2
  equatable: ^2.0.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-VariableFont_wdth,wght.ttf
    - family: Signika
      fonts:    
        - asset: assets/fonts/SignikaNegative-VariableFont_wght.ttf  
      